repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
  files_unchanged:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
template:
  prefix: JaneliaSciComp
  skip:
    - github_badges
    - igenomes
