contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #lightsheetrecon channel"
    url: https://nfcore.slack.com/channels/lightsheetrecon
    about: Discussion about the nf-core/lightsheetrecon pipeline
