contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #easifish channel"
    url: https://nfcore.slack.com/channels/easifish
    about: Discussion about the JaneliaSciComp/easifish pipeline
