createDataset:
  classname: net.preibisch.bigstitcher.spark.CreateDataset
  advancedArgs: []

resave:
  classname: net.preibisch.bigstitcher.spark.SparkResaveN5
  advancedArgs: []

detectInterestPoints:
  classname: net.preibisch.bigstitcher.spark.SparkInterestPointDetection
  advancedArgs:
    - '--channelId=1'
    - '--overlappingOnly'
    - '--onlyCompareOverlapTiles'
    - '--label=beads'
    - '--sigma=4.2'
    - '--threshold=0.008'
    - '--minIntensity=230'
    - '--maxIntensity=1800'
    - '--downsampleXY=2'
    - '--downsampleZ=1'

phaseCorrelationStitcher:
  classname: net.preibisch.bigstitcher.spark.SparkPhaseCorrelationPairwiseStitching
  advancedArgs: []

interestPointsStitcher:
  classname: net.preibisch.bigstitcher.spark.SparkRegisterWithInterestPoints
  advancedArgs:
    - '--label=beads'
    - '--channelId=1'
    - '--method=PRECISE_TRANSLATION'
    - '--searchRadius=1000'
    - '--transformationModel=TRANSLATION'
    - '--regularizationModel=NONE'
    - '--globalOptType=TWO_ROUND_SIMPLE'

duplicateTransformation:
  classname: net.preibisch.bigstitcher.spark.DuplicateTransformation
  advancedArgs:
    - '--duplicateMode=CHANNELS'
    - '--sourceId=1'
    - '--transformationsMode=REPLACE_ALL'

matchInterestPoints:
  classname: net.preibisch.bigstitcher.spark.SparkGeometricDescriptorMatching
  advancedArgs: []

solver:
  classname: net.preibisch.bigstitcher.spark.Solver
  advancedArgs: []

createContainer:
  classname: net.preibisch.bigstitcher.spark.CreateFusionContainer
  advancedArgs:
    - '--multiRes'
    - '--preserveAnisotropy'

fuse:
  classname: net.preibisch.bigstitcher.spark.SparkFusion
  advancedArgs:
    # fusion arg values:AVG_BLEND,CLOSEST_PIXEL_WINS
    - '--fusion=AVG_BLEND'
