ransac:
  blob_sizes: [6, 14]
  nspots: 5000
  num_sigma_max: 5
  cc_radius: 15
  match_threshold: 0.6
  max_spot_match_distance:
  point_matches_threshold: 15
  align_threshold: 2.0
  diagonal_constraint: 0.15
  fix_spots_count_threshold: 25
  fix_spot_detection_kwargs:
    blob_method: log
    background_subtract: false
    threshold: 0.0001
    threshold_rel: 0.001
    winsorize_limits: [0.01, 0.01]
  mov_spots_count_threshold: 25
  mov_spot_detection_kwargs:
    blob_method: log
    background_subtract: false
    threshold: 0.001
    threshold_rel: 0.01
    winsorize_limits: [0.01, 0.01]

global_align:
  ransac:
    # overriden parameters
    num_sigma_max: 5
    point_matches_threshold: 15
  affine:
    alignment_spacing: 2.0
    shrink_factors: [2]
    smooth_sigmas: [2]
    metric: MMI
    optimizer: RSGD
    optimizer_args:
      learningRate: 1.7
      minStep: 0.0001
      numberOfIterations: 4000

local_align:
  steps: [ransac, affine, deform]
  block_size: [128, 128, 128]
  block_overlap: 0.25
  transform_overlap: 0.1
  ransac:
    # overriden parameters
    alignment_spacing: 1
    num_sigma_max: 6
    point_matches_threshold: 15
    fix_spots_count_threshold: 20
    mov_spots_count_threshold: 20
  affine:
    alignment_spacing: [0.9,0.8,0.8]
    shrink_factors: [1]
    smooth_sigmas: [1]
    metric: MMI
    optimizer: RSGD
    optimizer_args:
      learningRate: 4
      minStep: 0
      numberOfIterations: 400
  deform:
    alignment_spacing: 0.9
    control_point_spacing: 40
    control_point_levels: [1]
    shrink_factors: [1]
    smooth_sigmas: [1.0]
    metric: MMI
    optimizer: RSGD
    optimizer_args:
      learningRate: 1.5
      minStep: 0.00001
      numberOfIterations: 100
  demons:
    iterations: [200, 150, 100, 50]
    smooth_sigmas: [4.0, 2.0, 1.0, 0.25]
    shrink_factors: [8, 4, 2, 1]
    variant: diffeomorphic # valid values: diffeomorphic, fast_symmetric, symmetric, demons
    field_smoothing_sigma: 2.5
    update_smoothing_sigma: 0.0
    smooth_displacement_field: true
    smooth_update_field: true
    max_rms_error: 0.0
    histogram_match: true
    histogram_match_levels: 1024
    histogram_match_points: 7
    histogram_match_threshold_at_mean: true
