channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - psutil>=7.1.3
  - pip:
    - git+https://github.com/JaneliaSciComp/bigstream@4a34f0b
    - git+https://github.com/JaneliaSciComp/cellpose-tools@c2f9a15
