name: dask_startscheduler
description: Start a Dask scheduler which runs until the terminate module is called
keywords:
  - dask
tools:
  - dask:
      description: Dask is a flexible library for parallel computing in Python.
      homepage: https://www.dask.org/
      documentation: https://docs.dask.org/en/stable/
      tool_dev_url: https://github.com/dask/dask
      licence: ["BSD 3-Clause License"]

input:
  - args:
      type: map
      description: |
        Groovy Map containing tool parameters. MUST follow the structure/keywords below and be provided via modules.config. Parameters must be set between quotes. (optional) parameters can be removed from the map, if they are not set. For default values, please check the documentation above.

        ```
        {
          [
            "with_dask_dashboard": (optional),
            "dask_scheduler_port": (optional),
            "dask_scheduler_start_timeout_secs": 120,
            "dask_scheduler_poll_interval_secs": 5,
          ]
        }
        ```
  - cluster_work_dir:
      type: path
      description: |
        The cluster work directory where the scheduler will run

output:
  - cluster_work_fullpath:
      type: string
      description: |
        Full path to the cluster work directory where the scheduler is running
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@cgoina"
